### ISSUE TITLE
Confirmation before deleting row/cols/table?

### ISSUE THREAD

**Issue by andre-brdoch** [ssfbank/sanity-plugin-byo-table#5]
Thank you so much for this fantastic plugin! This was exactly what I was looking for 😃

What do you think about adding confirmation dialogs before deleting rows/columns/the table? Right now it's pretty easy to accidentally delete the data.

If you want I could make a PR. I have this basically ready, since I was trying to fork sanity-datatable, before I found your plugin.

**Comment by roffelsaurus** [comment]
Hey, 

good to hear that it is useful to you!

Confirmation dialogs sounds fine. I'm not personally a fan of them in systems with undo ability like sanity. But I know most content editors are, so if you make a PR we can definitely make that the default :)

**Comment by andre-brdoch** [comment]
Done! let me know what you think 👍 

https://github.com/ssfbank/sanity-plugin-byo-table/pull/6/files
